name: fastapi-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - fastapi
  - uvicorn
  - python-multipart
  - pydantic
  - sqlalchemy
  - aiomysql
  - passlib=1.7.4
  - bcrypt
